WEBSOCKET ws://localhost:8080/chat
Content-Type: application/json // used only for IDE highlighting.
// Highlighting is applied for each message independently.


{
    "message": "Send when the WebSocket connection is opened"
}



###
### GET request to example server
GET http://localhost:8080/health

###
GET http://localhost:8080/metrics